name: Test Bypass

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_bypass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install curl_cffi tls_client typing_extensions
      - name: Run bypass test
        run: python test_bypass.py
